apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rucio
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/cvmfs-contrib/cvmfs-csi/blob/master/deployments/helm/cvmfs-csi
