apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-flux-pvc
  namespace: cvmfs-03
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1
  storageClassName: cvmfs
