apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rucio-dev
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/rucio/apps
  prune: true
  validation: client
